### ISSUE TITLE
digitalocean: droplets should be named after project

### ISSUE THREAD

**Issue by brenzi** [flex-dapps/gantree-lib-nodejs#27]
the droplets on digitalocean as generated by gantree-cli have very generic names. I'd like to test two different testnets with the same DO credentials, but then the droplets should be named after the project.

**Comment by DrTexx** [comment]
@brenzi I'm closing this issue as I've not received any updates from you yet.
If this issue hasn't been resolved by what I mentioned above please @mention me on in this thread.
Thanks!
